@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant 商户WEB系统 as A
participant 微信支付用户 as B
participant 微信客户端 as C
participant 商户后台系统 as D
participant 微信支付系统 as E
A -> D: 用户下订单
D -> D: 生成订单()
D -> E: 统一下单API()
E -> E: 生成预支付交易()
D <-- E: 返回预支付交易链接(code_url)
D -> D: 将链接生成二维码图片(code_url)
B <-- D: 二维码展示给用户()
B -> C: 用户打开微信扫一扫二维码()
C -> E: 提交扫码链接()
E -> E: 验证链接有效性()
C <-- E: 返回需要用户支付授权()
B -> C: 用户确认支付，输入密码()
C -> E: 提交支付授权()
E -> E: 验证授权，完成支付交易()
par 并行处理
    C <-- E: 返回支付结果，发送短信和微信消息提醒()
    D <- E: 异步通知商户支付结果()
    note over B,E
        参考地址：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_7&index=8
        注意：
        1、同样的通知可能会多次发送给商户系统。商户系统必须能够正确处理重复的通知。
        2、后台通知交互时，如果微信收到商户的应答不符合规范或超时，微信会判定本次通知失败，
        重新发送通知，直到成功为止（在通知一直不成功的情况下，微信总共会发起多次通知，
        通知频率为15s/15s/30s/3m/10m/20m/30m/30m/30m/60m/3h/3h/3h/6h/6h - 总计 24h4m），
        但微信不保证通知最终一定能成功。
        3、在订单状态不明或者没有收到微信支付结果通知的情况下，建议商户主动调用微信支付【查询订单API】确认订单状态。
        特别提醒：
        1、商户系统对于支付结果通知的内容一定要做签名验证,并校验返回的订单金额是否与商户侧的订单金额一致，
        防止数据泄漏导致出现“假通知”，造成资金损失。
        2、当收到通知进行处理时，首先检查对应业务数据的状态，判断该通知是否已经处理过，如果没有处理过再进行处理，
        如果处理过直接返回结果成功。在对业务数据进行状态检查和处理之前，要采用数据锁进行并发控制，
        以避免函数重入造成的数据混乱。
        3、技术人员可登进微信商户后台扫描加入接口报警群，获取接口告警信息。
     end note
    D --> E: 返回支付通知接收情况()
    A -> D: 间隔2秒查询一次，一直轮询60秒,查询订单支付状态。\n（轮询时间间隔和次数，商户可以根据自身业务场景灵活设置）
    note over B,C
    1）如果轮询商户查单接口返回支付成功，则给用户展示支付成功页。
    2）如果超过系统设置的时间，商户查单接口仍未返回支付成功，则退出轮询，提醒用户交易超时。
    end note
    alt 判断支付状态
        D -> E: 调用查询订单API()
        D <-- E: 返回支付状态()
    end
    note over D,E
    参考地址：https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=23_9&index=1
    【支付回调处理】
    商户后台需要准确、高效地处理微信支付发送的异步支付结果通知，并按接口规范把处理结果返回给微信支付。
    【定时轮询查单】
    如果长时间没有收到支付结果通知，商户后台应该定时轮询调用《微信支付查单接口》去核实订单状态。
    方案一
    以订单下单成功时间为基准（或者以前端支付返回成功或者报错后，第一次调用商户查单接口未成功的时间为基准），
    每隔5秒/30秒/1分钟/3分钟/5分钟/10分钟/30分钟调用《微信支付查单接口》查询一次，最后一次查询还是未返回支付成功状态，则停止后续查询，
    并调用《关单接口》关闭订单。（轮询时间间隔和次数，商户可以根据自身业务场景灵活设置）
    方案二
    定时任务每隔30秒启动一次，找出最近10分钟内创建并且未支付的订单，调用《微信支付查单接口》核实订单状态。
    系统记录订单查询的次数，在10次查询之后状态还是未支付成功，则停止后续查询，并调用《关单接口》关闭订单。
    （轮询时间间隔和次数，商户可以根据自身业务场景灵活设置）
    end note
end
D -> D: 发货操作()
@enduml
